---
title: "Neuroscience article search"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(jsonlite)
library(dplyr)
# Get all mesh terms:
api_request <- URLencode(paste0("http://195.148.31.154:8001/all_mesh_terms"))
all_terms <- fromJSON(api_request)
```

* Write Mesh-term(s) (*ex. Neurons*) and/or affiliation (*ex. University of Eastern Finland* or *Hiltunen*) and click **Search**
* You will get a list of articles according your search criteria

```{r}
inputPanel(
  fluidRow(
    column(12,
           selectInput(inputId = "term_mesh", label = "MeSH term(s):", choices = all_terms, selected = "Neurons", multiple = T),
           actionButton("search", label = "Search")
    )
  ),
  fluidRow(
    column(12, 
           textInput(inputId = "term_affiliation", label = "Affiliation/author:", value = "University of Eastern Finland")
    )
  )
)

jsondata <- eventReactive(input$search,{
  term_mesh <- input$term_mesh 
  term_affiliation <- input$term_affiliation
  api_request <- paste0("http://195.148.31.154:8001/", "articles?")
  if(is.null(term_mesh) & term_affiliation != ""){
    api_request <- paste0(api_request, "affiliation=", term_affiliation)
  }else if(term_mesh != "" & term_affiliation == ""){
    api_request <- paste0(api_request, paste0("mesh=", term_mesh, collapse = "&"))
  }else if(term_mesh != "" & term_affiliation != ""){
    api_request <- paste0(api_request, paste0("mesh=", term_mesh, collapse = "&"), "&affiliation=", term_affiliation)
  }else{
    api_request <- paste0("http://195.148.31.154:8001/", "articles", "&per_page=100")
  } 
  api_request <- URLencode(paste0(api_request, "&per_page=100"))
  jsondata <- fromJSON(api_request)
  if(!is.null(nrow(jsondata))) jsondata
  else tibble(title="No results found", pub_year=as.double(), pubmed_id=as.double(), abstract="", mesh="", authors="")
})

```


## Search results 

```{r}
output$tableDB <- DT::renderDataTable(jsondata()[, c("title", "pub_year")],  
                                      selection = list(mode = "single", selected = 1), 
                                      options = list(pageLength = 5), 
                                      rownames = FALSE
)
DT::dataTableOutput("tableDB")

title <- reactive({
  if(!is.null(jsondata()$title[input$tableDB_rows_selected])) jsondata()$title[input$tableDB_rows_selected]
  else{
    "No results"
  }
})
```


### `r renderText({title()})`
<!-- ## `r renderText({jsondata()$title[input$tableDB_rows_selected]})` -->

```{r}
renderText({paste(jsondata()$authors[[input$tableDB_rows_selected]]$l_name, jsondata()$authors[[input$tableDB_rows_selected]]$f_name, collapse = ", ")})
renderText({paste0("Published: ", jsondata()$pub_year[[input$tableDB_rows_selected]], " | ", "PubMed ID: ", jsondata()$pubmed_id[[input$tableDB_rows_selected]])})
# renderText({paste0("Link: ", "https://www.ncbi.nlm.nih.gov/pubmed/?term=", jsondata()$pubmed_id[[input$tableDB_rows_selected]],"")})
# renderText({
# })
#   tagList("LINK:", a("linkki", href=paste0("https://www.ncbi.nlm.nih.gov/pubmed/?term=", jsondata()$pubmed_id[[input$tableDB_rows_selected]])))  

```

#### Abstract

```{r}
renderText({jsondata()$abstract[input$tableDB_rows_selected]})
```


#### Keywords

```{r}
renderText({paste0(jsondata()$mesh[[input$tableDB_rows_selected]], collapse = ", ")})
# jsondata$mesh[[1]]
# paste0(jsondata$mesh[[1]], collapse = ", ")
```


#### Authors and affialiation

```{r}
renderText({paste0(jsondata()$authors[[input$tableDB_rows_selected]]$l_name, ", ", jsondata()$authors[[input$tableDB_rows_selected]]$f_name, " (",jsondata()$authors[[input$tableDB_rows_selected]]$affiliation,")", collapse = "; ")})
```

